version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookadmin
      MYSQL_PASSWORD: Book@1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://bookadmin:Book@1234@db:3306/bookstore"
      NODE_ENV: development
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
